### PR TITLE
Support for Laravel 10

### PR DESCRIPTION
**Pull request by wilfredchen**

### CODE REVIEW

**Comment by ziming** [comment]
Hi @techenby 

You may have forgotten to tag a new release :)

**Comment by driftingly** [comment]
@ziming @wilfredchen Released as [1.3.2](https://github.com/tighten/parental/releases/tag/v1.3.2)

Thanks @wilfredchen 🙌

**Comment by benholmen** [comment]
Looking at it again I think you might need to clean up the tags. There's a `1.3.2` and a `v1.3.2` tag.

**Comment by driftingly** [comment]
Rereleased as `v1.3.3` https://github.com/tighten/parental/releases/tag/v1.3.3
When doing the release the last tag with out the `v` prefix was not listed at the top of the tags so I missed it.  Thanks @benholmen for looking into the issue!

**Pull request merged**
